# TCL File Generated by Component Editor 14.1
# Wed Feb 18 23:27:24 JST 2015
# DO NOT MODIFY


# 
# avm_irq_sender "Avalon-MM IRQ sender" v1.0
# kimu_shu 2015.02.18.23:27:24
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module avm_irq_sender
# 
set_module_property DESCRIPTION ""
set_module_property NAME avm_irq_sender
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Peripherals"
set_module_property AUTHOR kimu_shu
set_module_property DISPLAY_NAME "Avalon-MM IRQ sender"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avm_irq_sender
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avm_irq_sender.vhd VHDL PATH avm_irq_sender.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IRQ_WIDTH INTEGER 1
set_parameter_property IRQ_WIDTH DEFAULT_VALUE 1
set_parameter_property IRQ_WIDTH DISPLAY_NAME IRQ_WIDTH
set_parameter_property IRQ_WIDTH TYPE INTEGER
set_parameter_property IRQ_WIDTH UNITS None
set_parameter_property IRQ_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point control_slave
# 
add_interface control_slave avalon end
set_interface_property control_slave addressUnits WORDS
set_interface_property control_slave associatedClock clock
set_interface_property control_slave associatedReset reset
set_interface_property control_slave bitsPerSymbol 8
set_interface_property control_slave burstOnBurstBoundariesOnly false
set_interface_property control_slave burstcountUnits WORDS
set_interface_property control_slave explicitAddressSpan 0
set_interface_property control_slave holdTime 0
set_interface_property control_slave linewrapBursts false
set_interface_property control_slave maximumPendingReadTransactions 0
set_interface_property control_slave maximumPendingWriteTransactions 0
set_interface_property control_slave readLatency 0
set_interface_property control_slave readWaitStates 0
set_interface_property control_slave readWaitTime 0
set_interface_property control_slave setupTime 0
set_interface_property control_slave timingUnits Cycles
set_interface_property control_slave writeWaitTime 0
set_interface_property control_slave ENABLED true
set_interface_property control_slave EXPORT_OF ""
set_interface_property control_slave PORT_NAME_MAP ""
set_interface_property control_slave CMSIS_SVD_VARIABLES ""
set_interface_property control_slave SVD_ADDRESS_GROUP ""

add_interface_port control_slave address address Input 1
add_interface_port control_slave write_n write_n Input 1
add_interface_port control_slave writedata writedata Input 32
add_interface_port control_slave read_n read_n Input 1
add_interface_port control_slave readdata readdata Output 32
set_interface_assignment control_slave embeddedsw.configuration.isFlash 0
set_interface_assignment control_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint "control_slave"
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset 0
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output irq_width

